stages:
  - build
  - publish_linux-x64
  
#  - analyze
#  - test

build_job:
    stage: build
    tags:
        - dotnetcorewin
    script:
        - dotnet build '.\src\MessengerWeb.sln'

publish_job_linux:
    stage: publish_linux-x64
    tags:
        - dotnetcorewin
    script:
        - Remove-Item \MessengerWeb_publish_linux\* -Recurse -Force
        - dotnet publish '.\src\Server\MessengerWeb.Server.csproj' -o \MessengerWeb_publish_linux --runtime linux-x64 --self-contained true
